### ISSUE TITLE
Add ddev-viteserve

### ISSUE THREAD

**Issue by fgeierst** [fgeierst/typo3-vite-demo#1]
https://github.com/torenware/ddev-viteserve

**Comment by mandrasch** [comment]
Hey, thanks for starting this! Just as optional side notes, don't know if helpful: 

Maybe these third party packages could be a good reference since they use a PHP-centric approach with `.php`-config-files:
- https://github.com/nystudio107/craft-vite (also works with DDEV)
    - https://nystudio107.com/docs/vite/
    - https://craftquest.io/courses/ddev-and-craft-cms-quick-start-guide ($)
- https://laravel-vite.dev/

_(The new official https://github.com/laravel/vite-plugin took another approach to tackle this by using a more NodeJS-centric approach. But this led to lengthy discussions regarding DDEV usage https://github.com/laravel/vite-plugin/issues/83. Personally I would'nt recommend this approach ;-)))_

Unfortunately I'm not a typo3 backend pro, but I'm happy to participate in testing!  ✅ Subscribed.
