### ISSUE TITLE
Add Vite backend integration

### ISSUE THREAD

**Issue by fgeierst** [fgeierst/typo3-vite-demo#2]
https://vitejs.dev/guide/backend-integration.html

**Comment by mandrasch** [comment]
Hey, thanks for starting this! Just as optional side notes, don't know if helpful: 

Maybe these third party packages could be a good reference since they use a PHP-centric approach with `.php`-config-files:
- https://github.com/nystudio107/craft-vite (also works with DDEV)
    - https://nystudio107.com/docs/vite/
    - https://craftquest.io/courses/ddev-and-craft-cms-quick-start-guide ($)
- https://laravel-vite.dev/

_(The new official https://github.com/laravel/vite-plugin took another approach to tackle this by using a more NodeJS-centric approach. But this led to lengthy discussions regarding DDEV usage https://github.com/laravel/vite-plugin/issues/83. Personally I wouldn't recommend this approach ;-)))_

Unfortunately I'm not a typo3 backend pro, but I'm happy to participate in testing!  ✅ Subscribed.

**Comment by fgeierst** [comment]
https://github.com/fgeierst/typo3-vite-demo/blob/master/packages/typo3_vite_demo/Configuration/TypoScript/setup.typoscript#L167

**TODO**: Add vite scripts only in development mode. In production mode read the hashed js and css file paths from manifest.json
See https://vitejs.dev/guide/backend-integration.html, Section 3.
