### ISSUE TITLE
Dependencies pnpm and tmux missing

### ISSUE THREAD

**Issue by vergissberlin** [fgeierst/typo3-vite-demo#9]
Hi,

in the devbox there are the dependencies for `pnpm`and `tmux` which are currently not included.
I don't know ddev very well, but there should be a way to set up it on install, isn't it?

Best regards,
André

**Comment by fgeierst** [comment]
Hi André, thanks thanks for raising this! This is coming from the [viteserve](https://github.com/torenware/ddev-viteserve) DDEV addon. A newer version of this addon has the option to [use npm instead of pnpm ](https://github.com/torenware/ddev-viteserve/issues/3), which is already installed in the default ddev docker image I think. About tmux I'm not sure, I'll have to look into it...

**Comment by fgeierst** [comment]
- `pnpm` is installed via the [Dockerfile.ddev-viteserve ](https://github.com/fgeierst/typo3-vite-demo/blob/3f0ccb73417c1352e6d5ea25faacb06cca080626/.ddev/web-build/Dockerfile.ddev-viteserve#L6).
  - You can also use `npm`, see [.ddev/.env](https://github.com/fgeierst/typo3-vite-demo/blob/3f0ccb73417c1352e6d5ea25faacb06cca080626/.ddev/.env)
- `tmux` is [available in Alpine Linux by default](https://pkgs.alpinelinux.org/packages?name=tmux), so no need to install ist.
